server:
  port: 8020
logging:
  level:
    com:
      memo: debug

---

spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: test

---

spring:
  config:
    activate:
      on-profile: prod